### ISSUE TITLE
飞机的图片应该放什么呢？

### ISSUE THREAD

**Issue by ZCpioneer** [ZCpioneer/planeGame#3]
飞机的图片是我随便找的，但是飞机的话，实际上是两张图片一直循环播放的，应该是有连贯性的，所以换什么好看呢？

**Comment by ZCpionner** [comment]
***
呀？

**Comment by ZCpionner** [comment]
> 飞机的图片是我随便找的，但是飞机的话，实际上是两张图片一直循环播放的，应该是有连贯性的，所以换什么好看呢？

放帅气炫酷的
